name: macOS builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [opt, fastbuild]

    steps:
    - uses: actions/checkout@v2

    - uses: bazelbuild/setup-bazelisk@v1

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel-macos-${{matrix.build_type}}

    - name: Bazel build and test
      run: bazel
        --noworkspace_rc
        test //... -s
        -c ${{matrix.build_type}}
        --copt=-Werror
        --copt=-std=c++17
